# Treinamento

### Carregando Arquivo de Treinamento (.csv)

In [9]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/Elianedantas/RedeNeuralPerceptronDiabetes/main/Dados_diabetes_treinamento.csv'
base_Treinamento = pd.read_csv(url,sep=',', encoding = 'latin1').values
print("---------------------------------")
print("Dados dos Pacientes - TREINAMENTO")
print("---------------------------------")
print(base_Treinamento)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Treinamento[:, 0:8])

print("----------------------------")
print("Classificação Supervisionada")
print("----------------------------")
print(base_Treinamento[:, 8])

---------------------------------
Dados dos Pacientes - TREINAMENTO
---------------------------------
[[  6.    148.     72.    ...   0.627  50.      1.   ]
 [  1.     85.     66.    ...   0.351  31.      0.   ]
 [  8.    183.     64.    ...   0.672  32.      1.   ]
 ...
 [  5.    121.     72.    ...   0.245  30.      0.   ]
 [  1.    126.     60.    ...   0.349  47.      1.   ]
 [  1.     93.     70.    ...   0.315  23.      0.   ]]
---------------------------------
Atributos de Entrada
---------------------------------
[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]
----------------------------
Classificação Supervisionada
----------------------------
[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1

### Pré-processamento de Dados

In [10]:
import numpy as np
from sklearn import preprocessing

# Binarizador de rótulo
#lb = preprocessing.LabelBinarizer()

#A saída da transformação é também conhecido como codificação 1-de-n
#Transforma valores categóricos equidistantes em valores binários equidistantes.
#Atributos categóricos com valores sim e não

#Atributos categóricos com valores pequenas e grandes

#Atributos categóricos com valores saudável e doente
normalizer = preprocessing.MinMaxScaler()

pregnancies = normalizer.fit_transform(np.array(base_Treinamento[:, 0]).reshape(-1,1))

glucose = normalizer.fit_transform(np.array(base_Treinamento[:, 1]).reshape(-1,1))

bloodPressure = normalizer.fit_transform(np.array(base_Treinamento[:, 2]).reshape(-1,1))

skinThickness = normalizer.fit_transform(np.array(base_Treinamento[:, 3]).reshape(-1,1))

insulin = normalizer.fit_transform(np.array(base_Treinamento[:, 4]).reshape(-1,1))

BMI = normalizer.fit_transform(np.array(base_Treinamento[:, 5]).reshape(-1,1))

diabetesPedigreeFunction = normalizer.fit_transform(np.array(base_Treinamento[:, 6]).reshape(-1,1))

age = normalizer.fit_transform(np.array(base_Treinamento[:, 7]).reshape(-1,1))

classes = base_Treinamento[:, 8]

#Concatenação de Atributos (Colunas)
atributos_norm = np.column_stack((pregnancies, glucose, bloodPressure, skinThickness, insulin, BMI, diabetesPedigreeFunction, age))
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_norm)

print("----------------------------------------")
print("Classificação Supervisionada - Numéricos")
print("----------------------------------------")
diagnostico_norm = np.hstack((classes))
print(diagnostico_norm)

--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[0.35294118 0.74371859 0.59016393 ... 0.50074516 0.23441503 0.48333333]
 [0.05882353 0.42713568 0.54098361 ... 0.39642325 0.11656704 0.16666667]
 [0.47058824 0.91959799 0.52459016 ... 0.34724292 0.25362938 0.18333333]
 ...
 [0.29411765 0.6080402  0.59016393 ... 0.390462   0.07130658 0.15      ]
 [0.05882353 0.63316583 0.49180328 ... 0.4485842  0.11571307 0.43333333]
 [0.05882353 0.46733668 0.57377049 ... 0.45305514 0.10119556 0.03333333]]
----------------------------------------
Classificação Supervisionada - Numéricos
----------------------------------------
[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1.
 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.

### Treinamento do Neurônio Perceptron

In [11]:
from sklearn.linear_model import Perceptron
# Treinamento do Perceptron a partir dos atributos de entrada e classificações
modelo = Perceptron()
modelo.fit(atributos_norm, diagnostico_norm)

# Acurácia do modelo, que é : 1 - (predições erradas / total de predições)
# Acurácia do modelo: indica uma performance geral do modelo.
# Dentre todas as classificações, quantas o modelo classificou corretamente;
# (VP+VN)/N
print('Acurácia: %.3f' % modelo.score(atributos_norm, diagnostico_norm))

Acurácia: 0.736


### ----------------------------------------------------------------------------

# Validação do Aprendizado

### Predição Simples

In [12]:
Luiz = [[148, 72, 35,0,	33.6,	0.627,50,0]]
print("Luiz", modelo.predict(Luiz))
Laura = [[143,94,33,146,36.6,0.254,51,1]]
print("Laura", modelo.predict(Laura))

Luiz [1.]
Laura [1.]


### Predição a partir de base de dados (.csv)

In [16]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/Elianedantas/RedeNeuralPerceptronDiabetes/main/Dados_diabetes_testes.csv'
base_Testes = pd.read_csv(url,sep=',', encoding = 'latin1').values
print("----------------------------")
print("Dados dos Pacientes - TESTES")
print("----------------------------")
print(base_Testes)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Testes[:, 0:8])

----------------------------
Dados dos Pacientes - TESTES
----------------------------
[[6.000e+00 1.480e+02 7.200e+01 3.500e+01 0.000e+00 3.360e+01 6.270e-01
  5.000e+01]
 [1.000e+00 8.500e+01 6.600e+01 2.900e+01 0.000e+00 2.660e+01 3.510e-01
  3.100e+01]
 [8.000e+00 1.830e+02 6.400e+01 0.000e+00 0.000e+00 2.330e+01 6.720e-01
  3.200e+01]
 [1.000e+00 8.900e+01 6.600e+01 2.300e+01 9.400e+01 2.810e+01 1.670e-01
  2.100e+01]
 [0.000e+00 1.370e+02 4.000e+01 3.500e+01 1.680e+02 4.310e+01 2.288e+00
  3.300e+01]
 [5.000e+00 1.160e+02 7.400e+01 0.000e+00 0.000e+00 2.560e+01 2.010e-01
  3.000e+01]
 [3.000e+00 7.800e+01 5.000e+01 3.200e+01 8.800e+01 3.100e+01 2.480e-01
  2.600e+01]
 [1.000e+01 1.150e+02 0.000e+00 0.000e+00 0.000e+00 3.530e+01 1.340e-01
  2.900e+01]
 [2.000e+00 1.970e+02 7.000e+01 4.500e+01 5.430e+02 3.050e+01 1.580e-01
  5.300e+01]
 [8.000e+00 1.250e+02 9.600e+01 0.000e+00 0.000e+00 0.000e+00 2.320e-01
  5.400e+01]
 [4.000e+00 1.100e+02 9.200e+01 0.000e+00 0.000e+00 3.760e+01 1

### Pré-processamento de Dados

In [17]:
import numpy as np
from sklearn import preprocessing

# Binarizador de rótulo
#lb = preprocessing.LabelBinarizer()

#A saída da transformação é também conhecido como codificação 1-de-n
#Transforma valores categóricos equidistantes em valores binários equidistantes.

normalizer = preprocessing.MinMaxScaler()

pregnancies = normalizer.fit_transform(np.array(base_Testes[:, 0]).reshape(-1,1))

glucose = normalizer.fit_transform(np.array(base_Testes[:, 1]).reshape(-1,1))

bloodPressure = normalizer.fit_transform(np.array(base_Testes[:, 2]).reshape(-1,1))

skinThickness = normalizer.fit_transform(np.array(base_Testes[:, 3]).reshape(-1,1))

insulin = normalizer.fit_transform(np.array(base_Testes[:, 4]).reshape(-1,1))

BMI = normalizer.fit_transform(np.array(base_Testes[:, 5]).reshape(-1,1))

diabetesPedigreeFunction = normalizer.fit_transform(np.array(base_Testes[:, 6]).reshape(-1,1))

age = normalizer.fit_transform(np.array(base_Testes[:, 7]).reshape(-1,1))

#Concatenação de Atributos (Colunas)
atributos_norm = np.column_stack((pregnancies,glucose,bloodPressure,skinThickness,insulin,BMI,diabetesPedigreeFunction,age))
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_norm)


--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[0.46153846 0.58823529 0.75       0.74468085 0.         0.73362445
  0.22887651 0.74358974]
 [0.07692308 0.05882353 0.6875     0.61702128 0.         0.58078603
  0.1007428  0.25641026]
 [0.61538462 0.88235294 0.66666667 0.         0.         0.50873362
  0.24976787 0.28205128]
 [0.07692308 0.09243697 0.6875     0.4893617  0.11111111 0.61353712
  0.01532033 0.        ]
 [0.         0.49579832 0.41666667 0.74468085 0.19858156 0.94104803
  1.         0.30769231]
 [0.38461538 0.31932773 0.77083333 0.         0.         0.55895197
  0.03110492 0.23076923]
 [0.23076923 0.         0.52083333 0.68085106 0.10401891 0.6768559
  0.05292479 0.12820513]
 [0.76923077 0.31092437 0.         0.         0.         0.77074236
  0.         0.20512821]
 [0.15384615 1.         0.72916667 0.95744681 0.64184397 0.66593886
  0.01114206 0.82051282]
 [0.61538462 0.39495798 1.         0.         0.         0.
  0.0

### Predição da Base

In [18]:
base_Predicao = modelo.predict((atributos_norm))
print("Classificações: ", base_Predicao)

Classificações:  [1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1.
 1. 1. 1. 0. 1. 0. 1. 1. 0. 0. 1.]


### Retorno aos valores Categóricos