# Treinamento

### Carregando Arquivo de Treinamento (.csv)

In [3]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/Elianedantas/RedeNeuralPerceptronDiabetes/main/Ex09_KNN/diabetes_treinamento_KNN.csv'
base_Treinamento = pd.read_csv(url,sep=',', encoding = 'latin1').values
print("--------------------------------------------------------")
print("Dados dos Pacientes - TREINAMENTO - Dimensão ",base_Treinamento.shape)
print("--------------------------------------------------------")
print(base_Treinamento)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Treinamento[:, 0:8])

print("----------------------------")
print("Classificação Supervisionada")
print("----------------------------")
print(base_Treinamento[:, 8])

--------------------------------------------------------
Dados dos Pacientes - TREINAMENTO - Dimensão  (522, 10)
--------------------------------------------------------
[[  4. 111.  72. ...  56.   1.   1.]
 [  5.  88.  66. ...  30.   0.   0.]
 [  8. 176.  90. ...  58.   1.   1.]
 ...
 [  1. 106.  76. ...  26.   0.   0.]
 [  2.  88.  58. ...  22.   0.   0.]
 [  5. 121.  72. ...  30.   0.   0.]]
---------------------------------
Atributos de Entrada
---------------------------------
[[  4.    111.     72.    ...  37.1     1.39   56.   ]
 [  5.     88.     66.    ...  24.4     0.342  30.   ]
 [  8.    176.     90.    ...  33.7     0.467  58.   ]
 ...
 [  1.    106.     76.    ...  37.5     0.197  26.   ]
 [  2.     88.     58.    ...  28.4     0.766  22.   ]
 [  5.    121.     72.    ...  26.2     0.245  30.   ]]
----------------------------
Classificação Supervisionada
----------------------------
[1. 0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 1

### Pré-processamento de Dados

In [4]:
import numpy as np
from sklearn import preprocessing


normalizer = preprocessing.MinMaxScaler()

pregnancies = normalizer.fit_transform(np.array(base_Treinamento[:, 0]).reshape(-1,1))

glucose = normalizer.fit_transform(np.array(base_Treinamento[:, 1]).reshape(-1,1))

bloodPressure = normalizer.fit_transform(np.array(base_Treinamento[:, 2]).reshape(-1,1))

skinThickness = normalizer.fit_transform(np.array(base_Treinamento[:, 3]).reshape(-1,1))

insulin = normalizer.fit_transform(np.array(base_Treinamento[:, 4]).reshape(-1,1))

BMI = normalizer.fit_transform(np.array(base_Treinamento[:, 5]).reshape(-1,1))

diabetesPedigreeFunction = normalizer.fit_transform(np.array(base_Treinamento[:, 6]).reshape(-1,1))

age = normalizer.fit_transform(np.array(base_Treinamento[:, 7]).reshape(-1,1))

classes = base_Treinamento[:, 8]



atributos_norm = np.column_stack((pregnancies, glucose, bloodPressure, skinThickness, insulin, BMI, diabetesPedigreeFunction, age))
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_norm)

print("----------------------------------------")
print("Classificação Supervisionada - Numéricos")
print("----------------------------------------")
diagnostico_norm = np.hstack((classes))
print(diagnostico_norm)

--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[0.26666667 0.55778894 0.59016393 ... 0.55290611 0.56020495 0.58333333]
 [0.33333333 0.44221106 0.54098361 ... 0.36363636 0.11272417 0.15      ]
 [0.53333333 0.88442211 0.73770492 ... 0.50223547 0.16609735 0.61666667]
 ...
 [0.06666667 0.53266332 0.62295082 ... 0.55886736 0.05081127 0.08333333]
 [0.13333333 0.44221106 0.47540984 ... 0.42324888 0.29376601 0.01666667]
 [0.33333333 0.6080402  0.59016393 ... 0.390462   0.07130658 0.15      ]]
----------------------------------------
Classificação Supervisionada - Numéricos
----------------------------------------
[1. 0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 1. 0. 1.
 1. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1.

### Treinamento do KNN (K-Nearest Neighbor)

In [5]:
from sklearn.neighbors import KNeighborsClassifier
# Treinamento do Knn a partir dos atributos de entrada e classificações com K=3
modelo = KNeighborsClassifier(n_neighbors=3)
modelo.fit(atributos_norm, diagnostico_norm)

# Acurácia do modelo, que é : 1 - (predições erradas / total de predições)
# Acurácia do modelo: indica uma performance geral do modelo.
# Dentre todas as classificações, quantas o modelo classificou corretamente;
# (VP+VN)/N
print('Acurácia: %.3f' % modelo.score(atributos_norm, diagnostico_norm))

Acurácia: 0.927


### ----------------------------------------------------------------------------

# Validação do Aprendizado

### Predição Simples

In [6]:
Luiz = [[0,0,1,1,0,1,0,1]]
Luiz_result = normalizer.fit_transform(Luiz)
print("Luiz", modelo.predict(Luiz))
Laura = [[1,1,0,1,0,1,1,1]]
Laura_result = normalizer.fit_transform(Laura)
print("Laura", modelo.predict(Laura))

Luiz [0.]
Laura [1.]


### Predição a partir de base de dados (.csv)

In [7]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/Elianedantas/RedeNeuralPerceptronDiabetes/main/Ex09_KNN/diabetes_testes_KNN.csv'
base_Testes = pd.read_csv(url,sep=',', encoding = 'latin1').values
print("----------------------------")
print("Dados dos Pacientes - TESTES")
print("----------------------------")
print(base_Testes)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Testes[:, 0:7])

----------------------------
Dados dos Pacientes - TESTES
----------------------------
[[6.000e+00 1.480e+02 7.200e+01 3.500e+01 0.000e+00 3.360e+01 6.270e-01
  5.000e+01]
 [1.000e+00 8.500e+01 6.600e+01 2.900e+01 0.000e+00 2.660e+01 3.510e-01
  3.100e+01]
 [8.000e+00 1.830e+02 6.400e+01 0.000e+00 0.000e+00 2.330e+01 6.720e-01
  3.200e+01]
 [1.000e+00 8.900e+01 6.600e+01 2.300e+01 9.400e+01 2.810e+01 1.670e-01
  2.100e+01]
 [0.000e+00 1.370e+02 4.000e+01 3.500e+01 1.680e+02 4.310e+01 2.288e+00
  3.300e+01]
 [5.000e+00 1.160e+02 7.400e+01 0.000e+00 0.000e+00 2.560e+01 2.010e-01
  3.000e+01]
 [3.000e+00 7.800e+01 5.000e+01 3.200e+01 8.800e+01 3.100e+01 2.480e-01
  2.600e+01]
 [1.000e+01 1.150e+02 0.000e+00 0.000e+00 0.000e+00 3.530e+01 1.340e-01
  2.900e+01]
 [2.000e+00 1.970e+02 7.000e+01 4.500e+01 5.430e+02 3.050e+01 1.580e-01
  5.300e+01]
 [8.000e+00 1.250e+02 9.600e+01 0.000e+00 0.000e+00 0.000e+00 2.320e-01
  5.400e+01]
 [4.000e+00 1.100e+02 9.200e+01 0.000e+00 0.000e+00 3.760e+01 1

### Pré-processamento de Dados

In [8]:
import numpy as np
from sklearn import preprocessing



normalizer = preprocessing.MinMaxScaler()

pregnancies = normalizer.fit_transform(np.array(base_Testes[:, 0]).reshape(-1,1))

glucose = normalizer.fit_transform(np.array(base_Testes[:, 1]).reshape(-1,1))

bloodPressure = normalizer.fit_transform(np.array(base_Testes[:, 2]).reshape(-1,1))

skinThickness = normalizer.fit_transform(np.array(base_Testes[:, 3]).reshape(-1,1))

insulin = normalizer.fit_transform(np.array(base_Testes[:, 4]).reshape(-1,1))

BMI = normalizer.fit_transform(np.array(base_Testes[:, 5]).reshape(-1,1))

diabetesPedigreeFunction = normalizer.fit_transform(np.array(base_Testes[:, 6]).reshape(-1,1))

age = normalizer.fit_transform(np.array(base_Testes[:, 7]).reshape(-1,1))




#Concatenação de Atributos (Colunas) 
atributos_norm = np.column_stack((pregnancies,glucose,bloodPressure,skinThickness,insulin,BMI,diabetesPedigreeFunction,age))
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_norm)

--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[0.46153846 0.58823529 0.75       0.74468085 0.         0.73362445
  0.22887651 0.74358974]
 [0.07692308 0.05882353 0.6875     0.61702128 0.         0.58078603
  0.1007428  0.25641026]
 [0.61538462 0.88235294 0.66666667 0.         0.         0.50873362
  0.24976787 0.28205128]
 [0.07692308 0.09243697 0.6875     0.4893617  0.11111111 0.61353712
  0.01532033 0.        ]
 [0.         0.49579832 0.41666667 0.74468085 0.19858156 0.94104803
  1.         0.30769231]
 [0.38461538 0.31932773 0.77083333 0.         0.         0.55895197
  0.03110492 0.23076923]
 [0.23076923 0.         0.52083333 0.68085106 0.10401891 0.6768559
  0.05292479 0.12820513]
 [0.76923077 0.31092437 0.         0.         0.         0.77074236
  0.         0.20512821]
 [0.15384615 1.         0.72916667 0.95744681 0.64184397 0.66593886
  0.01114206 0.82051282]
 [0.61538462 0.39495798 1.         0.         0.         0.
  0.0

### Predição da Base

In [12]:
base_Predicao = modelo.predict((atributos_norm))
print("Classificações: ", base_Predicao)

Classificações:  [0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0.
 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0.]


### Retorno aos valores Categóricos